// pyRound must agree with CPython's round(x, 4) on every case, ties included.
// The cases (and CPython's answers) are generated by the Python side.
import { pyRound } from "../core/pyround";

const cases: [number, number][] = JSON.parse(
  await Bun.file(new URL("../../spec/goldens/round_cases.json", import.meta.url).pathname).text(),
);

let bad = 0;
for (const [x, want] of cases) {
  const got = pyRound(x, 4);
  if (!Object.is(got, want) && got !== want) {
    if (bad < 8) console.log(`  MISMATCH x=${x} want=${want} got=${got}`);
    bad++;
  }
}
console.log(`pyRound vs CPython: ${cases.length - bad}/${cases.length} agree`);
if (bad) {
  console.log("PYROUND FAILED");
  process.exit(1);
}
console.log("PYROUND OK");
